[package]
name = "ids_sql"
version = "0.1.0"
authors = ["Pierre-François Gimenez <pierre-francois.gimenez@centralesupelec.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = "0.9"
regex = "1.5"
